<div class="<?php echo $this->escapeHtmlAttr($this->thumbs_width_extra_small) ?> <?php echo $this->escapeHtmlAttr($this->thumbs_width_small) ?> <?php echo $this->escapeHtmlAttr($this->thumbs_width_medium) ?>">
    <a href="<?php echo $this->escapeHtmlAttr($this->miniPhotoGalleryImageUrl($this->data['image'], false)) ?>" class="thumbnail fancybox" title="<?php echo $this->escapeHtmlAttr($this->data['description']) ?>">
        <img class="vertical-aligned" alt="<?php echo $this->escapeHtmlAttr($this->data['name']) ?>" src="<?php echo $this->escapeHtmlAttr($this->miniPhotoGalleryImageUrl($this->data['image'])) ?>" />
    </a>
</div>