<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'MiniPhotoGallery\Module'                                              => __DIR__ . '/Module.php',
    'MiniPhotoGallery\Controller\MiniPhotoGalleryAdministrationController' => __DIR__ . '/src/MiniPhotoGallery/Controller/MiniPhotoGalleryAdministrationController.php',
    'MiniPhotoGallery\Event\MiniPhotoGalleryEvent'                         => __DIR__ . '/src/MiniPhotoGallery/Event/MiniPhotoGalleryEvent.php',
    'MiniPhotoGallery\Exception\MiniPhotoGalleryException'                 => __DIR__ . '/src/MiniPhotoGallery/Exception/MiniPhotoGalleryException.php',
    'MiniPhotoGallery\Form\MiniPhotoGalleryCategory'                       => __DIR__ . '/src/MiniPhotoGallery/Form/MiniPhotoGalleryCategory.php',
    'MiniPhotoGallery\Form\MiniPhotoGalleryCategoryFilter'                 => __DIR__ . '/src/MiniPhotoGallery/Form/MiniPhotoGalleryCategoryFilter.php',
    'MiniPhotoGallery\Form\MiniPhotoGalleryImage'                          => __DIR__ . '/src/MiniPhotoGallery/Form/MiniPhotoGalleryImage.php',
    'MiniPhotoGallery\Model\MiniPhotoGalleryAdministration'                => __DIR__ . '/src/MiniPhotoGallery/Model/MiniPhotoGalleryAdministration.php',
    'MiniPhotoGallery\Model\MiniPhotoGalleryBase'                          => __DIR__ . '/src/MiniPhotoGallery/Model/MiniPhotoGalleryBase.php',
    'MiniPhotoGallery\Model\MiniPhotoGalleryWidget'                        => __DIR__ . '/src/MiniPhotoGallery/Model/MiniPhotoGalleryWidget.php',
    'MiniPhotoGallery\Service\MiniPhotoGallery'                            => __DIR__ . '/src/MiniPhotoGallery/Service/MiniPhotoGallery.php',
    'MiniPhotoGallery\View\Helper\MiniPhotoGalleryImageUrl'                => __DIR__ . '/src/MiniPhotoGallery/View/Helper/MiniPhotoGalleryImageUrl.php',
    'MiniPhotoGallery\View\Widget\MiniPhotoGalleryWidget'                  => __DIR__ . '/src/MiniPhotoGallery/View/Widget/MiniPhotoGalleryWidget.php',
    'MiniPhotoGallery\Test\MiniPhotoGalleryBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
];
